# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_imgdb', [dirname(__file__)])
        except ImportError:
            import _imgdb
            return _imgdb
        if fp is not None:
            try:
                _mod = imp.load_module('_imgdb', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _imgdb = swig_import_helper()
    del swig_import_helper
else:
    import _imgdb
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _imgdb.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _imgdb.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _imgdb.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _imgdb.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _imgdb.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _imgdb.SwigPyIterator_equal(self, x)

    def copy(self):
        return _imgdb.SwigPyIterator_copy(self)

    def next(self):
        return _imgdb.SwigPyIterator_next(self)

    def __next__(self):
        return _imgdb.SwigPyIterator___next__(self)

    def previous(self):
        return _imgdb.SwigPyIterator_previous(self)

    def advance(self, n):
        return _imgdb.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _imgdb.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _imgdb.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _imgdb.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _imgdb.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _imgdb.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _imgdb.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _imgdb.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _imgdb.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _imgdb.IntVector___nonzero__(self)

    def __bool__(self):
        return _imgdb.IntVector___bool__(self)

    def __len__(self):
        return _imgdb.IntVector___len__(self)

    def pop(self):
        return _imgdb.IntVector_pop(self)

    def __getslice__(self, i, j):
        return _imgdb.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _imgdb.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _imgdb.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _imgdb.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _imgdb.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _imgdb.IntVector___setitem__(self, *args)

    def append(self, x):
        return _imgdb.IntVector_append(self, x)

    def empty(self):
        return _imgdb.IntVector_empty(self)

    def size(self):
        return _imgdb.IntVector_size(self)

    def clear(self):
        return _imgdb.IntVector_clear(self)

    def swap(self, v):
        return _imgdb.IntVector_swap(self, v)

    def get_allocator(self):
        return _imgdb.IntVector_get_allocator(self)

    def begin(self):
        return _imgdb.IntVector_begin(self)

    def end(self):
        return _imgdb.IntVector_end(self)

    def rbegin(self):
        return _imgdb.IntVector_rbegin(self)

    def rend(self):
        return _imgdb.IntVector_rend(self)

    def pop_back(self):
        return _imgdb.IntVector_pop_back(self)

    def erase(self, *args):
        return _imgdb.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _imgdb.new_IntVector(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _imgdb.IntVector_push_back(self, x)

    def front(self):
        return _imgdb.IntVector_front(self)

    def back(self):
        return _imgdb.IntVector_back(self)

    def assign(self, n, x):
        return _imgdb.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _imgdb.IntVector_resize(self, *args)

    def insert(self, *args):
        return _imgdb.IntVector_insert(self, *args)

    def reserve(self, n):
        return _imgdb.IntVector_reserve(self, n)

    def capacity(self):
        return _imgdb.IntVector_capacity(self)
    __swig_destroy__ = _imgdb.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _imgdb.IntVector_swigregister
IntVector_swigregister(IntVector)

class LongIntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LongIntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LongIntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _imgdb.LongIntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _imgdb.LongIntVector___nonzero__(self)

    def __bool__(self):
        return _imgdb.LongIntVector___bool__(self)

    def __len__(self):
        return _imgdb.LongIntVector___len__(self)

    def pop(self):
        return _imgdb.LongIntVector_pop(self)

    def __getslice__(self, i, j):
        return _imgdb.LongIntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _imgdb.LongIntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _imgdb.LongIntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _imgdb.LongIntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _imgdb.LongIntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _imgdb.LongIntVector___setitem__(self, *args)

    def append(self, x):
        return _imgdb.LongIntVector_append(self, x)

    def empty(self):
        return _imgdb.LongIntVector_empty(self)

    def size(self):
        return _imgdb.LongIntVector_size(self)

    def clear(self):
        return _imgdb.LongIntVector_clear(self)

    def swap(self, v):
        return _imgdb.LongIntVector_swap(self, v)

    def get_allocator(self):
        return _imgdb.LongIntVector_get_allocator(self)

    def begin(self):
        return _imgdb.LongIntVector_begin(self)

    def end(self):
        return _imgdb.LongIntVector_end(self)

    def rbegin(self):
        return _imgdb.LongIntVector_rbegin(self)

    def rend(self):
        return _imgdb.LongIntVector_rend(self)

    def pop_back(self):
        return _imgdb.LongIntVector_pop_back(self)

    def erase(self, *args):
        return _imgdb.LongIntVector_erase(self, *args)

    def __init__(self, *args):
        this = _imgdb.new_LongIntVector(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _imgdb.LongIntVector_push_back(self, x)

    def front(self):
        return _imgdb.LongIntVector_front(self)

    def back(self):
        return _imgdb.LongIntVector_back(self)

    def assign(self, n, x):
        return _imgdb.LongIntVector_assign(self, n, x)

    def resize(self, *args):
        return _imgdb.LongIntVector_resize(self, *args)

    def insert(self, *args):
        return _imgdb.LongIntVector_insert(self, *args)

    def reserve(self, n):
        return _imgdb.LongIntVector_reserve(self, n)

    def capacity(self):
        return _imgdb.LongIntVector_capacity(self)
    __swig_destroy__ = _imgdb.delete_LongIntVector
    __del__ = lambda self: None
LongIntVector_swigregister = _imgdb.LongIntVector_swigregister
LongIntVector_swigregister(LongIntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _imgdb.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _imgdb.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _imgdb.DoubleVector___bool__(self)

    def __len__(self):
        return _imgdb.DoubleVector___len__(self)

    def pop(self):
        return _imgdb.DoubleVector_pop(self)

    def __getslice__(self, i, j):
        return _imgdb.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _imgdb.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _imgdb.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _imgdb.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _imgdb.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _imgdb.DoubleVector___setitem__(self, *args)

    def append(self, x):
        return _imgdb.DoubleVector_append(self, x)

    def empty(self):
        return _imgdb.DoubleVector_empty(self)

    def size(self):
        return _imgdb.DoubleVector_size(self)

    def clear(self):
        return _imgdb.DoubleVector_clear(self)

    def swap(self, v):
        return _imgdb.DoubleVector_swap(self, v)

    def get_allocator(self):
        return _imgdb.DoubleVector_get_allocator(self)

    def begin(self):
        return _imgdb.DoubleVector_begin(self)

    def end(self):
        return _imgdb.DoubleVector_end(self)

    def rbegin(self):
        return _imgdb.DoubleVector_rbegin(self)

    def rend(self):
        return _imgdb.DoubleVector_rend(self)

    def pop_back(self):
        return _imgdb.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _imgdb.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _imgdb.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _imgdb.DoubleVector_push_back(self, x)

    def front(self):
        return _imgdb.DoubleVector_front(self)

    def back(self):
        return _imgdb.DoubleVector_back(self)

    def assign(self, n, x):
        return _imgdb.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _imgdb.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _imgdb.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _imgdb.DoubleVector_reserve(self, n)

    def capacity(self):
        return _imgdb.DoubleVector_capacity(self)
    __swig_destroy__ = _imgdb.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _imgdb.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)


def queryImgData(dbId, sig1, sig2, sig3, avgl, numres, sketch, colorOnly):
    return _imgdb.queryImgData(dbId, sig1, sig2, sig3, avgl, numres, sketch, colorOnly)
queryImgData = _imgdb.queryImgData

def queryImgID(dbId, id, numres, sketch, colorOnly):
    return _imgdb.queryImgID(dbId, id, numres, sketch, colorOnly)
queryImgID = _imgdb.queryImgID

def queryImgBlob(dbId, data, numres, sketch, colorOnly):
    return _imgdb.queryImgBlob(dbId, data, numres, sketch, colorOnly)
queryImgBlob = _imgdb.queryImgBlob

def queryImgPath(dbId, path, numres, sketch, colorOnly):
    return _imgdb.queryImgPath(dbId, path, numres, sketch, colorOnly)
queryImgPath = _imgdb.queryImgPath

def queryImgDataForThresFast(tsigs, avgl, thresd, sketch):
    return _imgdb.queryImgDataForThresFast(tsigs, avgl, thresd, sketch)
queryImgDataForThresFast = _imgdb.queryImgDataForThresFast

def addImage(dbId, id, filename):
    return _imgdb.addImage(dbId, id, filename)
addImage = _imgdb.addImage

def addImageBlob(dbId, id, data):
    return _imgdb.addImageBlob(dbId, id, data)
addImageBlob = _imgdb.addImageBlob

def savedb(dbId, filename):
    return _imgdb.savedb(dbId, filename)
savedb = _imgdb.savedb

def loaddb(dbId, filename):
    return _imgdb.loaddb(dbId, filename)
loaddb = _imgdb.loaddb

def savealldbs(filename):
    return _imgdb.savealldbs(filename)
savealldbs = _imgdb.savealldbs

def loadalldbs(filename):
    return _imgdb.loadalldbs(filename)
loadalldbs = _imgdb.loadalldbs

def removeID(dbId, id):
    return _imgdb.removeID(dbId, id)
removeID = _imgdb.removeID

def resetdb(dbId):
    return _imgdb.resetdb(dbId)
resetdb = _imgdb.resetdb

def initDbase(dbId):
    return _imgdb.initDbase(dbId)
initDbase = _imgdb.initDbase

def closeDbase():
    return _imgdb.closeDbase()
closeDbase = _imgdb.closeDbase

def getImgCount(dbId):
    return _imgdb.getImgCount(dbId)
getImgCount = _imgdb.getImgCount

def isImageOnDB(dbId, id):
    return _imgdb.isImageOnDB(dbId, id)
isImageOnDB = _imgdb.isImageOnDB

def getImageHeight(dbId, id):
    return _imgdb.getImageHeight(dbId, id)
getImageHeight = _imgdb.getImageHeight

def getImageWidth(dbId, id):
    return _imgdb.getImageWidth(dbId, id)
getImageWidth = _imgdb.getImageWidth

def calcAvglDiff(dbId, id1, id2):
    return _imgdb.calcAvglDiff(dbId, id1, id2)
calcAvglDiff = _imgdb.calcAvglDiff

def calcDiff(dbId, id1, id2):
    return _imgdb.calcDiff(dbId, id1, id2)
calcDiff = _imgdb.calcDiff

def getImageAvgl(dbId, id1):
    return _imgdb.getImageAvgl(dbId, id1)
getImageAvgl = _imgdb.getImageAvgl

def getDBList():
    return _imgdb.getDBList()
getDBList = _imgdb.getDBList

def getImgIdList(dbId):
    return _imgdb.getImgIdList(dbId)
getImgIdList = _imgdb.getImgIdList

def isValidDB(dbId):
    return _imgdb.isValidDB(dbId)
isValidDB = _imgdb.isValidDB

def destroydb(dbId):
    return _imgdb.destroydb(dbId)
destroydb = _imgdb.destroydb

def removedb(dbId):
    return _imgdb.removedb(dbId)
removedb = _imgdb.removedb

def addKeywordImg(dbId, id, hash):
    return _imgdb.addKeywordImg(dbId, id, hash)
addKeywordImg = _imgdb.addKeywordImg

def addKeywordsImg(dbId, id, hashes):
    return _imgdb.addKeywordsImg(dbId, id, hashes)
addKeywordsImg = _imgdb.addKeywordsImg

def removeKeywordImg(dbId, id, hash):
    return _imgdb.removeKeywordImg(dbId, id, hash)
removeKeywordImg = _imgdb.removeKeywordImg

def removeAllKeywordImg(dbId, id):
    return _imgdb.removeAllKeywordImg(dbId, id)
removeAllKeywordImg = _imgdb.removeAllKeywordImg

def getKeywordsImg(dbId, id):
    return _imgdb.getKeywordsImg(dbId, id)
getKeywordsImg = _imgdb.getKeywordsImg

def queryImgIDKeywords(dbId, id, numres, kwJoinType, keywords, colorOnly):
    return _imgdb.queryImgIDKeywords(dbId, id, numres, kwJoinType, keywords, colorOnly)
queryImgIDKeywords = _imgdb.queryImgIDKeywords

def getAllImgsByKeywords(dbId, numres, kwJoinType, keywords):
    return _imgdb.getAllImgsByKeywords(dbId, numres, kwJoinType, keywords)
getAllImgsByKeywords = _imgdb.getAllImgsByKeywords

def getKeywordsVisualDistance(dbId, distanceType, keywords):
    return _imgdb.getKeywordsVisualDistance(dbId, distanceType, keywords)
getKeywordsVisualDistance = _imgdb.getKeywordsVisualDistance

def getKeywordsPopular(dbId, numres):
    return _imgdb.getKeywordsPopular(dbId, numres)
getKeywordsPopular = _imgdb.getKeywordsPopular
class clustersStruct(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, clustersStruct, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, clustersStruct, name)
    __repr__ = _swig_repr
    __swig_setmethods__["id"] = _imgdb.clustersStruct_id_set
    __swig_getmethods__["id"] = _imgdb.clustersStruct_id_get
    if _newclass:
        id = _swig_property(_imgdb.clustersStruct_id_get, _imgdb.clustersStruct_id_set)
    __swig_setmethods__["imgIds"] = _imgdb.clustersStruct_imgIds_set
    __swig_getmethods__["imgIds"] = _imgdb.clustersStruct_imgIds_get
    if _newclass:
        imgIds = _swig_property(_imgdb.clustersStruct_imgIds_get, _imgdb.clustersStruct_imgIds_set)
    __swig_setmethods__["diameter"] = _imgdb.clustersStruct_diameter_set
    __swig_getmethods__["diameter"] = _imgdb.clustersStruct_diameter_get
    if _newclass:
        diameter = _swig_property(_imgdb.clustersStruct_diameter_get, _imgdb.clustersStruct_diameter_set)

    def __init__(self):
        this = _imgdb.new_clustersStruct()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _imgdb.delete_clustersStruct
    __del__ = lambda self: None
clustersStruct_swigregister = _imgdb.clustersStruct_swigregister
clustersStruct_swigregister(clustersStruct)

class ClusterVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ClusterVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ClusterVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _imgdb.ClusterVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _imgdb.ClusterVector___nonzero__(self)

    def __bool__(self):
        return _imgdb.ClusterVector___bool__(self)

    def __len__(self):
        return _imgdb.ClusterVector___len__(self)

    def pop(self):
        return _imgdb.ClusterVector_pop(self)

    def __getslice__(self, i, j):
        return _imgdb.ClusterVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _imgdb.ClusterVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _imgdb.ClusterVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _imgdb.ClusterVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _imgdb.ClusterVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _imgdb.ClusterVector___setitem__(self, *args)

    def append(self, x):
        return _imgdb.ClusterVector_append(self, x)

    def empty(self):
        return _imgdb.ClusterVector_empty(self)

    def size(self):
        return _imgdb.ClusterVector_size(self)

    def clear(self):
        return _imgdb.ClusterVector_clear(self)

    def swap(self, v):
        return _imgdb.ClusterVector_swap(self, v)

    def get_allocator(self):
        return _imgdb.ClusterVector_get_allocator(self)

    def begin(self):
        return _imgdb.ClusterVector_begin(self)

    def end(self):
        return _imgdb.ClusterVector_end(self)

    def rbegin(self):
        return _imgdb.ClusterVector_rbegin(self)

    def rend(self):
        return _imgdb.ClusterVector_rend(self)

    def pop_back(self):
        return _imgdb.ClusterVector_pop_back(self)

    def erase(self, *args):
        return _imgdb.ClusterVector_erase(self, *args)

    def __init__(self, *args):
        this = _imgdb.new_ClusterVector(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _imgdb.ClusterVector_push_back(self, x)

    def front(self):
        return _imgdb.ClusterVector_front(self)

    def back(self):
        return _imgdb.ClusterVector_back(self)

    def assign(self, n, x):
        return _imgdb.ClusterVector_assign(self, n, x)

    def resize(self, *args):
        return _imgdb.ClusterVector_resize(self, *args)

    def insert(self, *args):
        return _imgdb.ClusterVector_insert(self, *args)

    def reserve(self, n):
        return _imgdb.ClusterVector_reserve(self, n)

    def capacity(self):
        return _imgdb.ClusterVector_capacity(self)
    __swig_destroy__ = _imgdb.delete_ClusterVector
    __del__ = lambda self: None
ClusterVector_swigregister = _imgdb.ClusterVector_swigregister
ClusterVector_swigregister(ClusterVector)


def getClusterDb(dbId, numClusters):
    return _imgdb.getClusterDb(dbId, numClusters)
getClusterDb = _imgdb.getClusterDb

def getClusterKeywords(dbId, numClusters, keywords):
    return _imgdb.getClusterKeywords(dbId, numClusters, keywords)
getClusterKeywords = _imgdb.getClusterKeywords

def getIdsBloomFilter(dbId):
    return _imgdb.getIdsBloomFilter(dbId)
getIdsBloomFilter = _imgdb.getIdsBloomFilter
class bloom_filter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, bloom_filter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, bloom_filter, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _imgdb.new_bloom_filter(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _imgdb.delete_bloom_filter
    __del__ = lambda self: None

    def insert(self, key):
        return _imgdb.bloom_filter_insert(self, key)

    def contains(self, key):
        return _imgdb.bloom_filter_contains(self, key)

    def size(self):
        return _imgdb.bloom_filter_size(self)

    def __iand__(self, filter):
        return _imgdb.bloom_filter___iand__(self, filter)

    def __ior__(self, filter):
        return _imgdb.bloom_filter___ior__(self, filter)

    def __ixor__(self, filter):
        return _imgdb.bloom_filter___ixor__(self, filter)
bloom_filter_swigregister = _imgdb.bloom_filter_swigregister
bloom_filter_swigregister(bloom_filter)

# This file is compatible with both classic and new-style classes.


